### ISSUE TITLE
Deployment to GitLab fails.

### ISSUE THREAD

**Issue by nibbleshift** [WP2Static/static-html-output-plugin#179]
If you enter your gitlab credentials on the "Deploy Static Website" page and click "Test Gitlab settings", it results in:

FAIL: Unable to complete test upload to GitLab

Is the Gitlab support broken?

**Comment by leonstafford** [comment]
Hi @nibbleshift, which version number of the plugin are you using? Gitlab test button should be working fine in latest official release

**Comment by nibbleshift** [comment]
Version 6.6.21

**Comment by leonstafford** [comment]
Hi @nibbleshift, that should be fine:

> fix deployment test button giving false positives

Was fixed in 6.6.21.

Are you able to check PHP server error logs for the error specifics if nothing's being shown in the plugin's UI or logs?

It may give us more info. If it comes back with an authentication issue, then would recommend to check your credentials again - ie, difference between storage zone and pull zone API keys
