### ISSUE TITLE
Fails for anything other than "Homepage only"

### ISSUE THREAD

**Issue by AnimatIan** [WP2Static/static-html-output-plugin#18]
I've recently started trying to use WP2Static to get a ZIP archive of the HTML for doc pages and blog posts.  However, I have only been able to get an archive with the "Homepage only" option.

"Initial crawl list" gives "6051 URLs were detected on your site that will be used to initiate the crawl. Other URLs will be discovered while crawling."

I have used Crawling settings with "Posts and pages only" and to exclude a large range of URLs, but WP2Static fails repeatedly when crawling, and sometimes at other times:
"Failed during "Analyzing site... this may take a few minutes (but it's worth it!)"
or
"Failed during Crawling"

(the fail point varies from day to day)

I enabled the Advanced / debug mode, but did not get any useful information.

P.S.  The plugin was enabled by my Wordpress admin and I only have access through the Wordpress UI.

**Comment by leonstafford** [comment]
@AnimatIan improvements coming in this V6.x.x branch, and also updating/maintaining 2 other WP 2 static plugins (top 3 pinned here: https://github.com/wp2static), so you should have more viable options again soon.

Closing this issue as more environmental and likely fixed in recent updates, will reopen if there's more specific error messages (error logging on by default in latest versions)
