### ISSUE TITLE
Deployment Batch Size (deployBatchSize) option ignored

### ISSUE THREAD

**Issue by oazish** [WP2Static/static-html-output-plugin#30]
Hi @leonstafford! 👋 I'm calling WP2Static via the WP-CLI to deploy a site from a multisite WordPress installation to GitHub pages, but WP2Static keeps deploying only one file per commit, regardless of the value of `deployBatchSize`. Needless to say, deploying one file per commit with a total of 1,500 files is extremely slow!

I've set my `deployBatchSize` to 100, as can be confirmed in the screenshot

![image](https://user-images.githubusercontent.com/49376306/56998730-47ac8880-6b61-11e9-9f78-7a5004523285.png)

and the WP-CLI

```
$ wp wp2static options get deployBatchSize --url=$MY_SITE_URL
100
```

Yet, WP2Static is turning a blind eye to this option and deploying only one file per commit. What is this madness? 😱

**Comment by leonstafford** [comment]
Current GitHub deployer implementation requires 1 commit per file in order to use the plugin's built-in deploycache. Older version was able to do singular commits, but not leverage any deploy caching. 

There is a new addon for V7 (WP2Static) vs this V6.x.x (named Static HTML Output Plugin from now) which does elegant GitHub deploys: https://github.com/Red-Madrone-Solutions/wp2s-addon-github

The workaround for V6, will be to either zip/folder deploy and use Git CLI tools to do your deploys or use GitLab or Bitbucket deploy options and set up an aut-mirror to GitHub (neither of those deployment options don't require the single commit per file).
