### ISSUE TITLE
Preformatted code HTML entity tag are changing real

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#42]
Sharing any code snippet would be possible once this is fixed. 

**How to repro?**
Write a new post with below code
`<meta name="robots" content="noindex">`
Export static site as ZIP, you will see like this in source code.
![image](https://user-images.githubusercontent.com/23408127/82193159-a5e60e00-9912-11ea-9be5-dcff894560b6.png)

This can lead to noindex web page. Once I faced this issue.

**Comment by leonstafford** [comment]
@thegulshankumar thanks for reporting this. It took me a while to figure out why this might be an issue. 

The answers/comments here give a good explanation of why we don't want to use any HTML tags as is within a `<code>` element: https://stackoverflow.com/q/11386586/1668057

So, a few options, none of them likely to be perfect for your workflow. 

I'd suggest this: when you add a code snippet in a web application using markdown, there's usually an option to specify the code language, so that the syntax can be properly highlighted. 

I haven't looked, but would assume that a widely-used code snippet inserter for WordPress would also offer specifying what language of code is in the snippet. If it's HTML/XML, then we'd hope they would encode HTML entities for us, ie

your

`<meta name="robots" content="noindex">`

would become 

`&#x3C;meta name=&#x22;robots&#x22; content=&#x22;noindex&#x22;&#x3E;`

OK, I just tseted the [Code Syntax Block](https://wordpress.org/plugins/code-syntax-block/), which does work as expected. Using this to render your HTML code snippets will properly escape them, make them prettier and optionally show line numbers:

![syntaxplugin](https://user-images.githubusercontent.com/2066833/82282745-bc07d300-99d3-11ea-8e03-5a7ba2c6d3e7.png)

So, I would suggest this is more an issue/limitation of WP's built-in options for displaying code. Their default Gutenberg block should have similar options to that plugin above, IMO. Perhaps they've already had a discussion on it and chosen not to or someone just needs to raise it to them (hint hint ;)

**Comment by leonstafford** [comment]
Closing this here. Will still be searchable for anyone else, but not an issue needing to be fixed within the plugin(s)

**Comment by thegulshankumar** [comment]
Hi Leon, 

**Sorry, my above screenshot is wrong to explain the issue.** 

_I should not have taken screenshot from Inspect Element tool as it shows what browser render for displaying, instead I should have taken from the (view-source:example.com) Browser source code._ 


Just to clarify, WordPress Block Editor does proper code element adding. Ref: screenshot.

![image](https://user-images.githubusercontent.com/23408127/82343801-e75ce300-9a10-11ea-99f4-fb8c07593163.png)

Request you to please re-check this issue. 

Thanks

**Comment by thegulshankumar** [comment]
WordPress already uses HTML entity tags but after export it turns real.

Please refer to line 192 to see difference
https://www.diffchecker.com/jpiLMsd6

**Comment by leonstafford** [comment]
cross-referencing our discussion of the issue being valid here: https://github.com/WP2Static/static-html-output-plugin/issues/47#issuecomment-631632033

**Comment by leonstafford** [comment]
should be fixed now, covered by tests
