### ISSUE TITLE
Issues with photo galleries

### ISSUE THREAD

**Issue by leonstafford** [WP2Static/static-html-output-plugin#76]
reported by user:

#######

Your plugin is working until I add a gallery. I have tried 3 now, and continuing, but I was hoping for a recommendation.

Different error messages on different attempts, but the failures all center around lines like the ones below with the words "photo" and "gallery" in them. I remove them and the conversion works.

************************ typical error message below ***************************

Uploading /home/dbcon0/public_html/wp-content/uploads/sites/3/wp-static-html-output-1591051924/wp-content/uploads/sites/3/photo-gallery/.original/spe_(10).jpg to wp-content/uploads/sites/3/photo-gallery/.original/ in S3
PUT'ing file to wp-content/uploads/sites/3/photo-gallery/.original/spe_(10).jpg in S3
Using S3 Endpoint aws-website-toyotasupraturbo-le34f.s3.us-east-1.amazonaws.com
S3 URL: http://aws-website-toyotasupraturbo-le34f.s3.us-east-1.amazonaws.com/wp-content/uploads/sites/3/photo-gallery/.original/spe_(10).jpg
API response code: 403

*************************************************************************************

**Comment by leonstafford** [comment]
Suggested workaround: If this is only failing when uploading to S3, due to those filenames, please try using the ZIP deployment method, download the zip and use AWS CLI tool to sync to S3. You'll then need to make a CloudFront invalidation call as an extra step if you're using CloudFront, just like the plugin does (plugin uses `/*` bulk invalidation of all objects).

**Comment by leonstafford** [comment]
needs some investigation if issue is persisting with latest changes

**Comment by debrucer** [comment]
Leon, Thank you for trying to address this issue for me. The error messages were different for the first three photo gallery plugins that I tried to sue. When I got to the fourth one, the message was the same as the 3rd... which got me to thinking.  I turned off your plugin, went to files in cPanel and blew away the two trees of crawling results. Then I enabled your plugin, blew away the S3 bucket contents, cleared the upload buffer, and tried again. It went just fine. It has since run fine three or four more times, so I suspect it's fixed. Since this is a WordPress multi-site, blowing away the results trees (plural, two) meant the other site needed rerunning, too.  I went back and tried a couple of the original gallery plugins, and they seemed to work, too. I'd say problem solved. Thank you very much for such a quick response. David

**Comment by leonstafford** [comment]
Thanks for putting in the time to troubleshoot and following up @debrucer!

I'll close this off for now, but it does seem like a situation that can be gotten into again and should hopefully addressed sooner or later as test coverage increases and more areas are stabilized.
