### ISSUE TITLE
Missing localhost destination URL port on export

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output-plugin#92]
If I keep destination URL set to
`http://html.localhost:4923` (Using Docker for testing)
![image](https://user-images.githubusercontent.com/23408127/84376571-f8a7a280-abfe-11ea-9780-bc3c664f15a7.png)

Output comes without port
`http://html.localhost`

![image](https://user-images.githubusercontent.com/23408127/84376408-baaa7e80-abfe-11ea-90c8-bfdab9aac5d0.png)

**Comment by leonstafford** [comment]
Part of this issue is that WP, at least with the TwentyTwenty theme, doesn't accommodate custom ports in it's canonical, protocol-relative URLs, so

http://html.localhost:4923

Will be 

`//html.localhost` even on your dev site's code, which is bad. It assume everyone's running WP on ports 80 or 443, which is going to be the 99% of WP users in production, but doesn't handle the others. It would be nice if it looked at what your Site URL or SERVER_URL were and only used protocol-relative URLs when it's on 80 or 443.

My plan is to just accept this and make sure we also include in our rewrite search pattern, a version of the URL, with ports stripped (we already look to replace protocol-relative URLs, but I guess it makes no sense to have a port along with a protocol-relative URL.

**Comment by leonstafford** [comment]
sorry @thegulshankumar, I was reading this as the other issue we chatted about, where the protocol-relative URLs were failing to be rewritten, ie for canonical link, which I've just put a fix in for. I probably won't be doing a fix for Destination URLs with custom ports, as the use case is low (now I sound like WP!) and many ways to get around it in any environment that would be using custom port names on their site (ie, it will have a proxy in front to port map, so 80 or 443 should be fine)

**Comment by leonstafford** [comment]
This is the issue I mistook this one for: https://github.com/WP2Static/static-html-output-plugin/issues/95

I'll close this one as won't fix for now, but may revisit in future if enough demand
